# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npm.taobao.org'

      - name: Install Node Modules
        run: npm install
      
      - name: Build Application
        run: npm run build
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: kimi-demo
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.yml
          if-no-files-found: error